### ISSUE TITLE
Fix crypto module in Bun

### ISSUE THREAD

**Issue by heeeyflo** [heeeyflo/envienc#9]
I faced the issue with running envienc on Bun – something wrong with `crypto.createCipheriv` in Bun's core library.

We need to fix it, and perhaps, introduce binary builds via built-in Bun bundler.

**Comment by Jarred-Sumner** [comment]
This is a bug in Bun. Can you file an issue and we will fix it?

**Comment by heeeyflo** [comment]
Fixed in https://github.com/oven-sh/bun/pull/6590
